#CONFIG VERSION, WILL ERASE YOUR CONFIG IF YOU ALTER.
version: 1.4

#Set if you the plugin to automatically alert you of plugin updates.
checkForUpdates: true

#Messages to set for when denying dropping.
dropDenyMessage: "&c [jNoDrops] &7You aren't allowed to drop items."
potionDenyMessage: "&c [jNoDrops] &7You aren't allowed to use potions."