# CONFIG VERSION, WILL ERASE YOUR CONFIG IF YOU ALTER.
version: 1.5

# Set if you the plugin to automatically alert you of plugin updates.
checkForUpdates: true

# Set to true to give player's item back when they drop it.
# Set to false for the items to be destroyed if they try to drop it.
shouldGetItemBack: true

# Messages to set for when denying dropping.
dropDenyMessage: "&c[JNoDrops] &7You aren't allowed to drop items."
potionDenyMessage: "&c[JNoDrops] &7You aren't allowed to use potions."