# CONFIG VERSION, WILL ERASE YOUR CONFIG IF YOU ALTER.
version: 1

# Set if you the plugin to automatically alert you of plugin updates.
checkForUpdates: true

# Messages to set for when denying dropping.
dropDenyMessage: "&c[JNoDrops] &7You aren't allowed to drop items."
potionDenyMessage: "&c[JNoDrops] &7You aren't allowed to use potions."