name: JNoDrops
author: Jordan Sne
version: @version@
description: Simple bukkit anti-drop plugin.
website: http://dev.bukkit.org/server-mods/jnodrops/

main: com.jordansne.jnodrops.JNoDrops
api-version: 1.13
commands:
  jnodrops:
    description: Administrative commands for JNoDrops.
    permission: jnodrops.admin
    aliases: [jnd]
permissions:
  jnodrops.*:
    children:
      jnodrops.dropitem: true
      jnodrops.pickupitem: true
      jnodrops.keepdroppeditem: true
      jnodrops.dropinventoryondeath: true
      jnodrops.usepotion: true
      jnodrops.savepotionbottle: true
      jnodrops.admin: true
  jnodrops.dropitem:
    default: op
    description: Allows players to drop items.
  jnodrops.pickupitem:
    default: op
    description: Allows players to pickup items.
  jnodrops.keepdroppeditem:
    default: op
    description: Allows players to keep the items they attempted to drop.
  jnodrops.dropinventoryondeath:
    default: op
    description: Players will drop their inventory upon death.
  jnodrops.usepotion:
    default: op
    description: Allows players to throw/use potions.
  jnodrops.savepotionbottle:
    default: op
    description: Players will keep their bottles after drinking.
  jnodrops.admin:
    default: op
    description: Allows admin commands to manage the plugin. 