name: JNoDrops
author: jsne10
version: 1.5.1
description: Simple bukkit anti-drop system.
website: http://dev.bukkit.org/server-mods/jnodrops/

main: com.jsne10.jnodrops.JNoDrops
commands:
  jnodrops:
    description: Administrative commands for jNoDrops.
    permission: jnodrops.admin
    aliases: [jnd]
permissions:
  jnodrops.*:
    children:
      jnodrops.candropitem: true
      jnodrops.getitemback: true
      jnodrops.canusepotion: true
      jnodrops.dropondeath: true
      jnodrops.savepotionbottle: true
      jnodrops.admin: true
  jnodrops.candropitem:
    default: op
    description: Allows players to drop item normally.
  jnodrops.getitemback:
    default: op
    description: Allows players to keep the items that are blocked from dropping.
  jnodrops.canusepotion:
    default: op
    description: Allows players to throw/use potions.
  jnodrops.dropondeath:
    default: op
    description: Players will drop their inventory upon death.
  jnodrops.savepotionbottle:
    default: op
    description: Players will keep or destory their bottles after drinking.
  jnodrops.admin:
    default: op
    description: Allows admin commands to manage the plugin. 