name: JNoDrops
author: Jordan Sne
version: @version@
description: Simple bukkit anti-drop plugin.
website: http://dev.bukkit.org/server-mods/jnodrops/

main: com.jordansne.jnodrops.JNoDrops
api-version: 1.13
commands:
  jnodrops:
    description: Administrative commands for JNoDrops.
    permission: jnodrops.admin
    aliases: [jnd]
permissions:
  jnodrops.*:
    children:
      jnodrops.dropitem: true
      jnodrops.pickupitem: true
      jnodrops.keepdroppeditem: true
      jnodrops.dropinventoryondeath: true
      jnodrops.usepotion: true
      jnodrops.keeppotionbottle: true
      jnodrops.admin: true
  jnodrops.dropitem:
    default: op
    description: Allows players to drop items.
  jnodrops.pickupitem:
    default: op
    description: Allows players to pickup items.
  jnodrops.keepdroppeditem:
    default: op
    description: Allows players to keep the items they attempted to drop.
  jnodrops.dropinventoryondeath:
    default: op
    description: Allows inventory drops when the player dies.
  jnodrops.usepotion:
    default: op
    description: Allows players to drink/throw potions.
  jnodrops.keeppotionbottle:
    default: op
    description: Allows players to keep the empty bottles of dranken potions.
  jnodrops.admin:
    default: op
    description: Allows players commands to use the admin command.