name: jNoDrops
author: jsne10
version: 1.4
description: Simple bukkit anti-drop system.
website: http://dev.bukkit.org/server-mods/jnodrops/

main: com.jsne10.nodrops.Main
commands:
  jnodrops:
    description: Administrative commands for jNoDrops.
    permission: jnodrops.admin
    aliases: [jnd]
permissions:
  jnodrops.*:
    children:
      jnodrops.candropitem: true
      jnodrops.candroppotion: true
      jnodrops.dropondeath: true
      jnodrops.admin: true
  jnodrops.candropitem:
    default: op
    description: Allows players to drop item normally. 
  jnodrops.candroppotion:
    default: op
    description: Allows players to throw potions.
  jnodrops.dropondeath:
    default: op
    description: Players will drop their inventory upon death.
  jnodrops.admin:
    default: op
    description: Allows admin commands to manage the plugin. 