name: Create Release
on:
  release:
    types: [ published ]

jobs:
  jar:
    name: Gradle shadowJar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Gradle Shadow Jar
        run: gradle shadowJar
      - name: Fetch Version
        id: fetch-version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/upload-artifact@v1
        with:
          name: JNoDrops-${{ steps.fetch-version.outputs.VERSION }}.jar
          path: build/libs/JNoDrops-${{ steps.fetch-version.outputs.VERSION }}.jar